snapshot 2025-11-07T15:31:01.972696+00:00

diff --git a/HACKING b/HACKING
--- a/HACKING
+++ b/HACKING
@@ -1,4 +1,4 @@
-    Copyright 2022-2024 Free Software Foundation, Inc.
+    Copyright 2022-2025 G. Branden Robinson
 
     Copying and distribution of this file, with or without
     modification, are permitted in any medium without royalty provided
@@ -26,7 +26,9 @@ Portability notes:
 
 * `std::size` is not available in C++98.  Use the `array_length`
   template function in src/include/lib.h instead of `sizeof` and
-  dividing.
+  dividing.  Types passed to template functions cannot be anonymous in
+  C++98; in other words, the "tag" of a `struct` or `enum` type must not
+  be empty.
 
 * C++98 lacks value initialization for array types.
 
@@ -119,8 +121,9 @@ Updating Copyright Notices
   accrete original status over time or a series of commits, it's fine to
   later update the notice to include the relevant (hopefully current)
   year in a stand-alone commit.  Use "git log --oneline" on a file to
-  gather commit IDs that justify the update and put them in the commit
-  message so that other people understand the basis of your claim.
+  gather commit IDs and change summaries that justify the update and put
+  them in the commit message so that other people understand the basis
+  of your claim.
 
 * It's okay to simply report a range of years in the copyright notice
   instead of a comma-separated list.  As far as GBR knows there is no
@@ -153,14 +156,36 @@ Here are some portability notes on writing automated tests.
     # emulate "seq 53"
     n=1; while [ $n -le 53 ]; do echo $n; n=$(( n + 1 )); done; unset n
 
+* The "wc" command on macOS can prefix the numeric count in its output
+  with spaces, which can be undesirable when storing that output to
+  variable that is later expanded within double quotes in the shell.
+
+  Here is a workaround.
+
+  res=$(whatever | wc -l)
+  res=$(( res + 0 )) || exit 99
+
+  If for some reason we get unacceptable non-integer garbage from "wc",
+  we exit the test script with the code reserved for "hard errors".
+  Shell arithmetic is unfortunately one of the many POSIX shell features
+  that Solaris 10's /bin/sh does not implement; see the "PROBLEMS" file.
+
 * The "od" command on macOS can put extra space characters (i.e., spaces
   that don't correspond to the input) at the ends of lines when using
-  the "od -t c" format; GNU od does not.
+  the "-t c" format; GNU od does not.
 
   So a regex like this that works with GNU od:
     grep -Eqx '0000000 +A +\\b +B +\\b +C       D +\\n'
-  might need to be weakened to the following on macOS.
+  might need to be weakened to the following to work on macOS.
     grep -Eqx '0000000 +A +\\b +B +\\b +C       D +\\n *'
+
+* The "od" command on macOS puts extra space characters between the
+  hexadecimal values when using the "-t x1" format; GNU od does not.
+
+  So a regex like this that works with GNU od:
+    grep -q '81 30 55 81 30 56 81 6c e2'
+  might need to be weakened to the following to work on macOS.
+    grep -q '81  *30  *55  *81  *30  *56  *81  *6c  *e2'
 
 * The "od" command on macOS does not respect the environment variable
   assignment "LC_ALL=C" when processing byte values 127<x<256 decimal
@@ -174,6 +199,9 @@ Here are some portability notes on writing automated tests.
   octal number for each byte in the character." (p. 538)  The language
   in Issue 7 (2018) appears unchanged.
     https://pubs.opengroup.org/onlinepubs/9699919799/utilities/od.html )
+
+* Prior to POSIX.1-2024, the meaning of the sequence `\]` in a basic or
+  extended regular expression is undefined.  Spell it as `]` instead.
 
 * macOS sed requires semicolons after commands even if they are followed
   immediately by a closing brace.
@@ -221,17 +249,56 @@ Here are some portability notes on writing automated tests.
     };
     }
 
+* Solaris 10's /usr/bin/cksum output is non-conforming with XPG4.  It
+  uses tabs as field delimiters instead of spaces.
+
+* Solaris 10's /usr/bin/grep is non-conforming with XPG4; it lacks
+  support for the `-E`, `-F`, `-q`, and `-x` options.
+
+* Solaris 10's /bin/sh is non-conforming with XPG4; it does not support
+  POSIX parameter expansion syntax.
+
+* Solaris 10's /usr/bin/tr exits with an error if you try to use a POSIX
+  character class (such as "[:cntrl:]") in any locale but "C".
+
+* Solaris 10's /usr/xpg4/bin/sh is non-conforming with XPG4.
+  (Good job, guys!)
+
+  Its "unset" builtin is buggy.  (The /usr/bin/sh in Solaris 11 does not
+  have this problem.)
+
+  We sometimes must use the "unset" shell builtin command to prevent
+  environment variables from confounding test results.
+
+  POSIX says "[u]nsetting a variable ... that was not previously set is
+  not considered an error and will not cause the shell to abort."
+
+  Nevertheless this builtin returns an error exit status in this
+  circumstance.
+
+  $ /usr/xpg4/bin/sh -c 'unset _NON_EXISTENT_XYZ; echo $?'
+  1
+
+  You may want to check for this misbehavior and skip the test if
+  running under an afflicted shell.
+
+  if ! unset VARIABLE_OF_INTEREST
+  then
+      echo "unable to clear environment; skipping" >&2
+      exit 77
+  fi
 
 Updating gnulib
 ---------------
 
-Here's how to update the submodule, using that project's "stable-202407"
+Here's how to update the submodule, using that project's "stable-202501"
 branch as an example.  From the root of your checkout:
 
   $ cd gnulib
-  $ git checkout -b stable-202407 --track origin/stable-202407
   $ git pull
+  $ git checkout -b stable-202501 --track origin/stable-202501
   $ cd ..
+  $ git add gnulib
   $ editor ChangeLog # log it
   $ git add ChangeLog
   $ git commit
@@ -240,6 +307,7 @@ It's likely a good idea to update the "bootstrap" script at the same
 time (not necessarily in the same commit, however).
 
   $ ./bootstrap --bootstrap-sync
+  $ git add bootstrap
   $ editor ChangeLog # log it
   $ git add ChangeLog
   $ git commit
