snapshot 2026-03-04T01:22:18.775487+00:00

diff --git a/contrib/mom/examples/test-mom.sh.in b/contrib/mom/examples/test-mom.sh.in
--- a/contrib/mom/examples/test-mom.sh.in
+++ b/contrib/mom/examples/test-mom.sh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (C) 2018-2025 Free Software Foundation, Inc.
+# Copyright 2018-2025 Free Software Foundation, Inc.
 #
 # This file is part of groff, the GNU roff typesetting system.
 #
@@ -16,7 +16,6 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
-#
 
 builddir="@abs_top_builddir@"
 have_urw_fonts="@groff_have_urw_fonts@"
@@ -43,7 +42,7 @@ for cmd in pdfinfo pdfimages
 do
     if ! command -v $cmd >/dev/null
     then
-        echo "cannot locate '$cmd' command; skipping test" >&2
+        echo "$0: cannot locate '$cmd' command; skipping" >&2
         exit 77 # skip
     fi
 done
@@ -86,6 +85,8 @@ check_has_images()
     fi
 }
 
+# TODO: Make this a "hard error" (status 99).  See, e.g.,
+# "font/devpdf/tests/check-default-foundry.sh.in".
 for k in $examples
 do
     if ! [ -f "$examplesdir"/$k ]
diff --git a/font/devpdf/tests/check-default-foundry.sh.in b/font/devpdf/tests/check-default-foundry.sh.in
--- a/font/devpdf/tests/check-default-foundry.sh.in
+++ b/font/devpdf/tests/check-default-foundry.sh.in
@@ -85,8 +85,8 @@ test -z "$fail" || exit
 
 if [ "$ghostscript" = no ] || [ "$ghostscript" = missing ]
 then
-    echo "Ghostscript not available; skipping check for any further" \
-         "fonts in the default foundry" >&2
+    echo "$0: Ghostscript not available; skipping check for any" \
+        "further fonts in the default foundry" >&2
     exit 77 # skip
 fi
 
@@ -94,13 +94,13 @@ foundry="$devpdf_fontbuilddir"/Foundry
 
 if ! test -f "$foundry"
 then
-    echo "cannot locate Foundry file at $foundry" >&2
+    echo "$0: cannot locate Foundry file at '$foundry'" >&2
     exit 99 # hard error
 fi
 
 if ! grep -q "BEGIN URW" "$foundry"
 then
-    echo "URW fonts not available; skipping check for any further" \
+    echo "$0: URW fonts not available; skipping check for any further" \
          "fonts in the default foundry" >&2
     exit 77 # skip
 fi
diff --git a/font/devpdf/tests/check-urw-foundry.sh.in b/font/devpdf/tests/check-urw-foundry.sh.in
--- a/font/devpdf/tests/check-urw-foundry.sh.in
+++ b/font/devpdf/tests/check-urw-foundry.sh.in
@@ -27,7 +27,7 @@ urwfontsdir=@urwfontsdir@
 
 if [ -z "$urwfontsdir" ]
 then
-    echo "URW fonts not found at configuration time; skipping" >&2
+    echo "$0: URW fonts not found at configuration time; skipping" >&2
     exit 77 # skip
 fi
 
