Frozen autocommit 2024-02-01 06:47:52.332834

diff --git a/contrib/mom/examples/test-mom.sh.in b/contrib/mom/examples/test-mom.sh.in
--- a/contrib/mom/examples/test-mom.sh.in
+++ b/contrib/mom/examples/test-mom.sh.in
@@ -1,19 +1,19 @@
 #!/bin/sh
 #
 # Copyright (C) 2018-2020 Free Software Foundation, Inc.
-# 
+#
 # This file is part of groff.
-# 
+#
 # groff is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free
 # Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
-# 
+#
 # groff is distributed in the hope that it will be useful, but WITHOUT ANY
 # WARRANTY; without even the implied warranty of MERCHANTABILITY or
 # FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
@@ -34,15 +34,15 @@ list="
   "
 
 if test "$have_urw_fonts" != "yes"; then
-    echo "No URW fonts, mom examples cannot be correctly generated"
-    exit 77
+    echo "URW fonts needed to generate mom examples; skipping test" >&2
+    exit 77 # skip
 fi
 
 for cmd in pdfinfo pdfimages
 do
     if ! command -v $cmd >/dev/null
     then
-        echo "cannot locate '$cmd' command; skipping" >&2
+        echo "cannot locate '$cmd' command; skipping test" >&2
         exit 77 # skip
     fi
 done
@@ -90,3 +90,5 @@ check_has_images "$examplesdir/typesetting.pdf"
 check_has_images "$examplesdir/slide-demo.pdf"
 
 exit $ret
+
+# vim:set ai et sw=4 ts=4 tw=72:
